Added dropdowns to the menu
ComputerScienceHouse/CSHMembersPortal pull request #131
Opened 2022-07-06 18:26 UTC by viv-codes

2022-07-06 18:26 UTC, viv-codes commented
![image](https://user-images.githubusercontent.com/79525734/177617981-d6feb68b-c969-4169-8f3d-daab320344a0.png)

2022-07-07 02:51 UTC, galenguyer approved these changes
LGTM

2022-07-07 02:51 UTC, merged

2022-07-07 02:52 UTC, galenguyer requested changes

2022-07-07 02:52 UTC, galenguyer commented on templates/navbar.html
> +          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ section.name }}</a>
Ack, this shouldn't be `example.com`

2022-07-07 02:53 UTC, viv-codes commented on templates/navbar.html
> +          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ section.name }}</a>
Will PR and fix immediately.