Add vault to services
ComputerScienceHouse/CSHMembersPortal pull request #163
Opened 2024-10-21 14:18 UTC by Mobmaker55

2024-10-23 20:56 UTC, esoccoli requested changes
The icon you used for Vault doesnt appear to exist. When I run your changes locally, all the other icons appear fine, but vault just doesnt have an icon

2026-03-27 14:23 UTC, BigSpaceships commented
<img width="154" height="133" alt="image" src="https://github.com/user-attachments/assets/894a86d4-8ab2-4417-ac77-6eef132dd113" />
I did a thing

2026-03-27 14:23 UTC, BigSpaceships approved these changes
yippee!

2026-03-27 14:47 UTC, pikachu0542 approved these changes
lgtm

2026-03-27 14:48 UTC, merged